### ISSUE TITLE
How to train a model

### ISSUE THREAD

**Issue by CHIGIRI19** [divyakraman/SALAD_SourcefreeActiveLabelAgnosticDomainAdaptation#1]
The code "from dataset.TargetDataset import TargetDataSet" is not avaliable, how to create a file named dataset? I mean what data I show place in the dataset?

**Comment by divyakraman** [comment]
Ah sorry, due to company policies, we were not allowed to release the full codebase and only released portions of the code pertained to the key contributions in the model. To write the dataloader code for your dataset, you can follow one of the domain adaptation codebases such as https://github.com/wasidennis/AdaptSegNet
